const data = [
  {
    filename: "PorttitorPede.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/PorttitorPede.mp3",
    hangiGun: "12-12-2022",
    avgArray: 8109,
    greaterAvgArray: 1906,
  },
  {
    filename: "Etiam.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Etiam.avi",
    hangiGun: "8-3-2022",
    avgArray: 869,
    greaterAvgArray: 5997,
  },
  {
    filename: "BlanditNonInterdum.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/BlanditNonInterdum.ppt",
    hangiGun: "1-25-2023",
    avgArray: 2078,
    greaterAvgArray: 8362,
  },
  {
    filename: "Auctor.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Auctor.mp3",
    hangiGun: "2-18-2022",
    avgArray: 7402,
    greaterAvgArray: 972,
  },
  {
    filename: "DuisAc.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/DuisAc.xls",
    hangiGun: "11-14-2022",
    avgArray: 1953,
    greaterAvgArray: 5897,
  },
  {
    filename: "AugueA.jpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/AugueA.jpeg",
    hangiGun: "11-29-2022",
    avgArray: 2816,
    greaterAvgArray: 2241,
  },
  {
    filename: "NecDuiLuctus.png",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/NecDuiLuctus.png",
    hangiGun: "11-7-2022",
    avgArray: 6892,
    greaterAvgArray: 4659,
  },
  {
    filename: "AnteVivamusTortor.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/AnteVivamusTortor.mp3",
    hangiGun: "6-10-2022",
    avgArray: 6067,
    greaterAvgArray: 1812,
  },
  {
    filename: "LigulaPellentesqueUltrices.doc",
    dosyaAdiniBul:
      "C:/Users/johnsmith/Documents/LigulaPellentesqueUltrices.doc",
    hangiGun: "6-23-2022",
    avgArray: 3162,
    greaterAvgArray: 1540,
  },
  {
    filename: "CurabiturIn.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/CurabiturIn.avi",
    hangiGun: "1-16-2023",
    avgArray: 7875,
    greaterAvgArray: 1674,
  },
  {
    filename: "VitaeConsectetuerEget.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/VitaeConsectetuerEget.avi",
    hangiGun: "9-30-2022",
    avgArray: 5671,
    greaterAvgArray: 4254,
  },
  {
    filename: "HacHabitassePlatea.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/HacHabitassePlatea.xls",
    hangiGun: "5-18-2022",
    avgArray: 2624,
    greaterAvgArray: 5853,
  },
  {
    filename: "Nulla.doc",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Nulla.doc",
    hangiGun: "2-9-2023",
    avgArray: 2424,
    greaterAvgArray: 5063,
  },
  {
    filename: "Dolor.jpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Dolor.jpeg",
    hangiGun: "7-1-2022",
    avgArray: 3098,
    greaterAvgArray: 9002,
  },
  {
    filename: "LaciniaSapien.doc",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/LaciniaSapien.doc",
    hangiGun: "4-21-2022",
    avgArray: 4672,
    greaterAvgArray: 1170,
  },
  {
    filename: "CongueEtiamJusto.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/CongueEtiamJusto.ppt",
    hangiGun: "9-17-2022",
    avgArray: 4454,
    greaterAvgArray: 1296,
  },
  {
    filename: "Lorem.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Lorem.ppt",
    hangiGun: "10-26-2022",
    avgArray: 8783,
    greaterAvgArray: 5655,
  },
  {
    filename: "SapienDignissim.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/SapienDignissim.ppt",
    hangiGun: "3-22-2022",
    avgArray: 1760,
    greaterAvgArray: 3217,
  },
  {
    filename: "UtSuscipitA.mpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/UtSuscipitA.mpeg",
    hangiGun: "9-4-2022",
    avgArray: 4653,
    greaterAvgArray: 3693,
  },
  {
    filename: "LoremQuisqueUt.png",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/LoremQuisqueUt.png",
    hangiGun: "4-25-2022",
    avgArray: 5042,
    greaterAvgArray: 1485,
  },
  {
    filename: "VestibulumAliquet.pdf",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/VestibulumAliquet.pdf",
    hangiGun: "11-19-2022",
    avgArray: 1067,
    greaterAvgArray: 8153,
  },
  {
    filename: "EuFelis.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/EuFelis.mp3",
    hangiGun: "1-10-2023",
    avgArray: 3154,
    greaterAvgArray: 5620,
  },
  {
    filename: "InLectusPellentesque.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/InLectusPellentesque.mp3",
    hangiGun: "5-22-2022",
    avgArray: 7865,
    greaterAvgArray: 3381,
  },
  {
    filename: "Nullam.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Nullam.ppt",
    hangiGun: "4-9-2022",
    avgArray: 7923,
    greaterAvgArray: 9762,
  },
  {
    filename: "MaurisViverra.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/MaurisViverra.ppt",
    hangiGun: "9-13-2022",
    avgArray: 1189,
    greaterAvgArray: 7720,
  },
  {
    filename: "QuamSuspendissePotenti.tiff",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/QuamSuspendissePotenti.tiff",
    hangiGun: "7-19-2022",
    avgArray: 1627,
    greaterAvgArray: 1959,
  },
  {
    filename: "Vel.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Vel.mp3",
    hangiGun: "9-27-2022",
    avgArray: 4106,
    greaterAvgArray: 2011,
  },
  {
    filename: "DuisMattisEgestas.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/DuisMattisEgestas.xls",
    hangiGun: "6-18-2022",
    avgArray: 182,
    greaterAvgArray: 602,
  },
  {
    filename: "Sapien.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Sapien.mp3",
    hangiGun: "2-12-2022",
    avgArray: 454,
    greaterAvgArray: 1175,
  },
  {
    filename: "VelNullaEget.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/VelNullaEget.xls",
    hangiGun: "11-6-2022",
    avgArray: 4264,
    greaterAvgArray: 384,
  },
  {
    filename: "MaurisLaoreet.txt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/MaurisLaoreet.txt",
    hangiGun: "5-31-2022",
    avgArray: 9794,
    greaterAvgArray: 3277,
  },
  {
    filename: "IpsumPraesentBlandit.mov",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/IpsumPraesentBlandit.mov",
    hangiGun: "2-11-2022",
    avgArray: 5513,
    greaterAvgArray: 6685,
  },
  {
    filename: "InHac.tiff",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/InHac.tiff",
    hangiGun: "8-13-2022",
    avgArray: 7980,
    greaterAvgArray: 7938,
  },
  {
    filename: "VelEstDonec.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/VelEstDonec.mp3",
    hangiGun: "12-30-2022",
    avgArray: 3381,
    greaterAvgArray: 4907,
  },
  {
    filename: "LaciniaEget.pdf",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/LaciniaEget.pdf",
    hangiGun: "11-2-2022",
    avgArray: 8391,
    greaterAvgArray: 2234,
  },
  {
    filename: "Leo.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Leo.mp3",
    hangiGun: "11-11-2022",
    avgArray: 2971,
    greaterAvgArray: 9100,
  },
  {
    filename: "Molestie.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Molestie.ppt",
    hangiGun: "1-9-2023",
    avgArray: 2274,
    greaterAvgArray: 3210,
  },
  {
    filename: "MassaDonec.png",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/MassaDonec.png",
    hangiGun: "4-20-2022",
    avgArray: 2983,
    greaterAvgArray: 4681,
  },
  {
    filename: "ErosElementumPellentesque.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/ErosElementumPellentesque.xls",
    hangiGun: "8-6-2022",
    avgArray: 2725,
    greaterAvgArray: 6284,
  },
  {
    filename: "AcDiam.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/AcDiam.avi",
    hangiGun: "7-1-2022",
    avgArray: 6738,
    greaterAvgArray: 2051,
  },
  {
    filename: "Lacinia.mov",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Lacinia.mov",
    hangiGun: "2-4-2023",
    avgArray: 403,
    greaterAvgArray: 6127,
  },
  {
    filename: "MaurisMorbi.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/MaurisMorbi.mp3",
    hangiGun: "4-22-2022",
    avgArray: 3038,
    greaterAvgArray: 3931,
  },
  {
    filename: "Nam.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Nam.ppt",
    hangiGun: "5-15-2022",
    avgArray: 9102,
    greaterAvgArray: 4770,
  },
  {
    filename: "Mi.pdf",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Mi.pdf",
    hangiGun: "3-18-2022",
    avgArray: 161,
    greaterAvgArray: 9598,
  },
  {
    filename: "Justo.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Justo.ppt",
    hangiGun: "4-1-2022",
    avgArray: 8904,
    greaterAvgArray: 6485,
  },
  {
    filename: "EuNibhQuisque.gif",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/EuNibhQuisque.gif",
    hangiGun: "5-31-2022",
    avgArray: 439,
    greaterAvgArray: 1886,
  },
  {
    filename: "CongueVivamusMetus.jpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/CongueVivamusMetus.jpeg",
    hangiGun: "9-8-2022",
    avgArray: 9667,
    greaterAvgArray: 390,
  },
  {
    filename: "EgetCongueEget.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/EgetCongueEget.avi",
    hangiGun: "6-29-2022",
    avgArray: 7333,
    greaterAvgArray: 8388,
  },
  {
    filename: "PulvinarNulla.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/PulvinarNulla.xls",
    hangiGun: "4-15-2022",
    avgArray: 5965,
    greaterAvgArray: 8656,
  },
  {
    filename: "MagnisDisParturient.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/MagnisDisParturient.mp3",
    hangiGun: "10-4-2022",
    avgArray: 1240,
    greaterAvgArray: 8759,
  },
  {
    filename: "LigulaSuspendisseOrnare.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/LigulaSuspendisseOrnare.ppt",
    hangiGun: "12-21-2022",
    avgArray: 2801,
    greaterAvgArray: 6887,
  },
  {
    filename: "TristiqueEst.jpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/TristiqueEst.jpeg",
    hangiGun: "7-3-2022",
    avgArray: 113,
    greaterAvgArray: 9984,
  },
  {
    filename: "Pede.mpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Pede.mpeg",
    hangiGun: "7-5-2022",
    avgArray: 5048,
    greaterAvgArray: 1365,
  },
  {
    filename: "VestibulumProinEu.jpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/VestibulumProinEu.jpeg",
    hangiGun: "10-21-2022",
    avgArray: 3682,
    greaterAvgArray: 7530,
  },
  {
    filename: "SitAmetEleifend.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/SitAmetEleifend.xls",
    hangiGun: "10-9-2022",
    avgArray: 3749,
    greaterAvgArray: 7249,
  },
  {
    filename: "MetusArcuAdipiscing.jpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/MetusArcuAdipiscing.jpeg",
    hangiGun: "8-14-2022",
    avgArray: 2300,
    greaterAvgArray: 1361,
  },
  {
    filename: "NullaFacilisiCras.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/NullaFacilisiCras.avi",
    hangiGun: "9-15-2022",
    avgArray: 499,
    greaterAvgArray: 4949,
  },
  {
    filename: "PellentesqueUltricesPhasellus.gif",
    dosyaAdiniBul:
      "C:/Users/johnsmith/Documents/PellentesqueUltricesPhasellus.gif",
    hangiGun: "3-24-2022",
    avgArray: 4098,
    greaterAvgArray: 4478,
  },
  {
    filename: "JustoSollicitudinUt.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/JustoSollicitudinUt.ppt",
    hangiGun: "11-5-2022",
    avgArray: 5126,
    greaterAvgArray: 7535,
  },
  {
    filename: "Dapibus.tiff",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Dapibus.tiff",
    hangiGun: "8-21-2022",
    avgArray: 1978,
    greaterAvgArray: 5867,
  },
  {
    filename: "Magna.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Magna.ppt",
    hangiGun: "6-19-2022",
    avgArray: 900,
    greaterAvgArray: 284,
  },
  {
    filename: "VulputateNonummy.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/VulputateNonummy.mp3",
    hangiGun: "6-21-2022",
    avgArray: 8496,
    greaterAvgArray: 4529,
  },
  {
    filename: "Bibendum.doc",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Bibendum.doc",
    hangiGun: "3-23-2022",
    avgArray: 7716,
    greaterAvgArray: 6889,
  },
  {
    filename: "MorbiVelLectus.tiff",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/MorbiVelLectus.tiff",
    hangiGun: "6-20-2022",
    avgArray: 6672,
    greaterAvgArray: 2824,
  },
  {
    filename: "CongueVivamus.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/CongueVivamus.xls",
    hangiGun: "8-10-2022",
    avgArray: 3050,
    greaterAvgArray: 8320,
  },
  {
    filename: "ConvallisEget.tiff",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/ConvallisEget.tiff",
    hangiGun: "12-12-2022",
    avgArray: 6383,
    greaterAvgArray: 9912,
  },
  {
    filename: "MorbiNonLectus.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/MorbiNonLectus.avi",
    hangiGun: "4-24-2022",
    avgArray: 403,
    greaterAvgArray: 6810,
  },
  {
    filename: "Quis.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Quis.ppt",
    hangiGun: "3-23-2022",
    avgArray: 5353,
    greaterAvgArray: 9123,
  },
  {
    filename: "RutrumNequeAenean.pdf",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/RutrumNequeAenean.pdf",
    hangiGun: "7-26-2022",
    avgArray: 8494,
    greaterAvgArray: 755,
  },
  {
    filename: "Sapien.doc",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Sapien.doc",
    hangiGun: "9-19-2022",
    avgArray: 3948,
    greaterAvgArray: 3017,
  },
  {
    filename: "Lectus.tiff",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Lectus.tiff",
    hangiGun: "7-30-2022",
    avgArray: 9090,
    greaterAvgArray: 4764,
  },
  {
    filename: "NibhIn.jpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/NibhIn.jpeg",
    hangiGun: "7-11-2022",
    avgArray: 9400,
    greaterAvgArray: 3933,
  },
  {
    filename: "CrasIn.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/CrasIn.ppt",
    hangiGun: "4-15-2022",
    avgArray: 4953,
    greaterAvgArray: 3191,
  },
  {
    filename: "AugueQuam.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/AugueQuam.xls",
    hangiGun: "8-18-2022",
    avgArray: 4623,
    greaterAvgArray: 996,
  },
  {
    filename: "Non.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Non.avi",
    hangiGun: "12-19-2022",
    avgArray: 8423,
    greaterAvgArray: 3382,
  },
  {
    filename: "ConsequatLectusIn.txt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/ConsequatLectusIn.txt",
    hangiGun: "8-4-2022",
    avgArray: 2212,
    greaterAvgArray: 9973,
  },
  {
    filename: "HacHabitassePlatea.pdf",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/HacHabitassePlatea.pdf",
    hangiGun: "7-17-2022",
    avgArray: 2971,
    greaterAvgArray: 1475,
  },
  {
    filename: "Augue.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Augue.ppt",
    hangiGun: "9-20-2022",
    avgArray: 3174,
    greaterAvgArray: 6256,
  },
  {
    filename: "UtOdio.tiff",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/UtOdio.tiff",
    hangiGun: "10-20-2022",
    avgArray: 6739,
    greaterAvgArray: 5872,
  },
  {
    filename: "FelisSedInterdum.jpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/FelisSedInterdum.jpeg",
    hangiGun: "7-11-2022",
    avgArray: 3932,
    greaterAvgArray: 5397,
  },
  {
    filename: "MolestieLoremQuisque.txt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/MolestieLoremQuisque.txt",
    hangiGun: "11-29-2022",
    avgArray: 4297,
    greaterAvgArray: 5198,
  },
  {
    filename: "Faucibus.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Faucibus.xls",
    hangiGun: "6-14-2022",
    avgArray: 8475,
    greaterAvgArray: 2935,
  },
  {
    filename: "Tincidunt.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Tincidunt.ppt",
    hangiGun: "10-22-2022",
    avgArray: 3243,
    greaterAvgArray: 3658,
  },
  {
    filename: "IpsumAliquam.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/IpsumAliquam.ppt",
    hangiGun: "8-13-2022",
    avgArray: 9405,
    greaterAvgArray: 5290,
  },
  {
    filename: "FaucibusOrciLuctus.txt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/FaucibusOrciLuctus.txt",
    hangiGun: "3-12-2022",
    avgArray: 768,
    greaterAvgArray: 3647,
  },
  {
    filename: "PedeVenenatis.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/PedeVenenatis.ppt",
    hangiGun: "9-23-2022",
    avgArray: 6864,
    greaterAvgArray: 5163,
  },
  {
    filename: "DuiMaecenas.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/DuiMaecenas.ppt",
    hangiGun: "7-19-2022",
    avgArray: 9732,
    greaterAvgArray: 3680,
  },
  {
    filename: "AcLeo.mpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/AcLeo.mpeg",
    hangiGun: "5-24-2022",
    avgArray: 6887,
    greaterAvgArray: 8732,
  },
  {
    filename: "IdMassaId.pdf",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/IdMassaId.pdf",
    hangiGun: "12-31-2022",
    avgArray: 3115,
    greaterAvgArray: 5538,
  },
  {
    filename: "LigulaSitAmet.jpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/LigulaSitAmet.jpeg",
    hangiGun: "12-24-2022",
    avgArray: 3771,
    greaterAvgArray: 3941,
  },
  {
    filename: "AtIpsum.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/AtIpsum.mp3",
    hangiGun: "2-8-2023",
    avgArray: 6521,
    greaterAvgArray: 6836,
  },
  {
    filename: "Placerat.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Placerat.xls",
    hangiGun: "10-10-2022",
    avgArray: 4983,
    greaterAvgArray: 5724,
  },
  {
    filename: "ImperdietNullam.mov",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/ImperdietNullam.mov",
    hangiGun: "12-12-2022",
    avgArray: 5194,
    greaterAvgArray: 2263,
  },
  {
    filename: "EuMassa.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/EuMassa.xls",
    hangiGun: "10-18-2022",
    avgArray: 3864,
    greaterAvgArray: 439,
  },
  {
    filename: "QuisTurpis.jpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/QuisTurpis.jpeg",
    hangiGun: "1-29-2023",
    avgArray: 6872,
    greaterAvgArray: 9494,
  },
  {
    filename: "SitAmet.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/SitAmet.ppt",
    hangiGun: "5-6-2022",
    avgArray: 2290,
    greaterAvgArray: 3203,
  },
  {
    filename: "UtNullaSed.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/UtNullaSed.xls",
    hangiGun: "6-14-2022",
    avgArray: 293,
    greaterAvgArray: 290,
  },
  {
    filename: "MaurisLacinia.mov",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/MaurisLacinia.mov",
    hangiGun: "8-13-2022",
    avgArray: 5976,
    greaterAvgArray: 6686,
  },
  {
    filename: "Eros.jpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Eros.jpeg",
    hangiGun: "6-2-2022",
    avgArray: 5931,
    greaterAvgArray: 6498,
  },
  {
    filename: "PotentiInEleifend.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/PotentiInEleifend.avi",
    hangiGun: "1-7-2023",
    avgArray: 4869,
    greaterAvgArray: 971,
  },
  {
    filename: "NecSem.jpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/NecSem.jpeg",
    hangiGun: "5-16-2022",
    avgArray: 1007,
    greaterAvgArray: 7468,
  },
  {
    filename: "RidiculusMusEtiam.doc",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/RidiculusMusEtiam.doc",
    hangiGun: "11-1-2022",
    avgArray: 9705,
    greaterAvgArray: 9279,
  },
  {
    filename: "LigulaVehiculaConsequat.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/LigulaVehiculaConsequat.xls",
    hangiGun: "7-15-2022",
    avgArray: 4789,
    greaterAvgArray: 4069,
  },
  {
    filename: "SitAmet.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/SitAmet.mp3",
    hangiGun: "2-7-2023",
    avgArray: 2944,
    greaterAvgArray: 2387,
  },
  {
    filename: "FelisDonec.gif",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/FelisDonec.gif",
    hangiGun: "6-14-2022",
    avgArray: 8167,
    greaterAvgArray: 4365,
  },
  {
    filename: "DisParturientMontes.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/DisParturientMontes.ppt",
    hangiGun: "6-12-2022",
    avgArray: 6200,
    greaterAvgArray: 8083,
  },
  {
    filename: "VelitDonecDiam.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/VelitDonecDiam.ppt",
    hangiGun: "7-26-2022",
    avgArray: 1216,
    greaterAvgArray: 7993,
  },
  {
    filename: "IpsumPrimisIn.tiff",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/IpsumPrimisIn.tiff",
    hangiGun: "5-14-2022",
    avgArray: 1951,
    greaterAvgArray: 9849,
  },
  {
    filename: "ConvallisNuncProin.tiff",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/ConvallisNuncProin.tiff",
    hangiGun: "1-3-2023",
    avgArray: 8497,
    greaterAvgArray: 8234,
  },
  {
    filename: "Ipsum.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Ipsum.mp3",
    hangiGun: "12-18-2022",
    avgArray: 1345,
    greaterAvgArray: 8882,
  },
  {
    filename: "LacusMorbiQuis.pdf",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/LacusMorbiQuis.pdf",
    hangiGun: "6-20-2022",
    avgArray: 3183,
    greaterAvgArray: 882,
  },
  {
    filename: "EgetSemperRutrum.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/EgetSemperRutrum.mp3",
    hangiGun: "5-5-2022",
    avgArray: 5676,
    greaterAvgArray: 6112,
  },
  {
    filename: "ConsequatMetusSapien.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/ConsequatMetusSapien.avi",
    hangiGun: "1-19-2023",
    avgArray: 7575,
    greaterAvgArray: 1175,
  },
  {
    filename: "HendreritAtVulputate.tiff",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/HendreritAtVulputate.tiff",
    hangiGun: "12-17-2022",
    avgArray: 6666,
    greaterAvgArray: 9523,
  },
  {
    filename: "At.pdf",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/At.pdf",
    hangiGun: "9-1-2022",
    avgArray: 1244,
    greaterAvgArray: 3772,
  },
  {
    filename: "VitaeNisl.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/VitaeNisl.mp3",
    hangiGun: "1-4-2023",
    avgArray: 1155,
    greaterAvgArray: 6958,
  },
  {
    filename: "Tristique.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Tristique.mp3",
    hangiGun: "9-29-2022",
    avgArray: 2690,
    greaterAvgArray: 4710,
  },
  {
    filename: "Turpis.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Turpis.xls",
    hangiGun: "5-23-2022",
    avgArray: 3410,
    greaterAvgArray: 4675,
  },
  {
    filename: "Suspendisse.txt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Suspendisse.txt",
    hangiGun: "8-16-2022",
    avgArray: 281,
    greaterAvgArray: 9902,
  },
  {
    filename: "LobortisSapien.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/LobortisSapien.xls",
    hangiGun: "5-12-2022",
    avgArray: 1692,
    greaterAvgArray: 5639,
  },
  {
    filename: "Molestie.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Molestie.avi",
    hangiGun: "3-21-2022",
    avgArray: 5133,
    greaterAvgArray: 5888,
  },
  {
    filename: "NullamVarius.pdf",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/NullamVarius.pdf",
    hangiGun: "9-29-2022",
    avgArray: 2644,
    greaterAvgArray: 5395,
  },
  {
    filename: "NullaAcEnim.jpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/NullaAcEnim.jpeg",
    hangiGun: "8-20-2022",
    avgArray: 1966,
    greaterAvgArray: 3016,
  },
  {
    filename: "SitAmetConsectetuer.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/SitAmetConsectetuer.ppt",
    hangiGun: "4-16-2022",
    avgArray: 4214,
    greaterAvgArray: 2833,
  },
  {
    filename: "NullaUltrices.tiff",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/NullaUltrices.tiff",
    hangiGun: "11-10-2022",
    avgArray: 5074,
    greaterAvgArray: 518,
  },
  {
    filename: "IdNisl.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/IdNisl.xls",
    hangiGun: "6-20-2022",
    avgArray: 5139,
    greaterAvgArray: 1338,
  },
  {
    filename: "Mauris.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Mauris.ppt",
    hangiGun: "4-15-2022",
    avgArray: 4457,
    greaterAvgArray: 3933,
  },
  {
    filename: "Erat.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Erat.xls",
    hangiGun: "5-24-2022",
    avgArray: 1346,
    greaterAvgArray: 8039,
  },
  {
    filename: "AcNibh.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/AcNibh.xls",
    hangiGun: "4-2-2022",
    avgArray: 5939,
    greaterAvgArray: 1201,
  },
  {
    filename: "TinciduntAnteVel.gif",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/TinciduntAnteVel.gif",
    hangiGun: "4-21-2022",
    avgArray: 7366,
    greaterAvgArray: 1620,
  },
  {
    filename: "VestibulumQuam.txt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/VestibulumQuam.txt",
    hangiGun: "11-21-2022",
    avgArray: 6542,
    greaterAvgArray: 585,
  },
  {
    filename: "VolutpatDuiMaecenas.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/VolutpatDuiMaecenas.avi",
    hangiGun: "8-2-2022",
    avgArray: 3533,
    greaterAvgArray: 8453,
  },
  {
    filename: "Lacus.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Lacus.avi",
    hangiGun: "4-16-2022",
    avgArray: 9782,
    greaterAvgArray: 5541,
  },
  {
    filename: "NullaNunc.tiff",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/NullaNunc.tiff",
    hangiGun: "7-13-2022",
    avgArray: 7310,
    greaterAvgArray: 1541,
  },
  {
    filename: "OdioConsequat.mov",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/OdioConsequat.mov",
    hangiGun: "12-22-2022",
    avgArray: 4569,
    greaterAvgArray: 8287,
  },
  {
    filename: "EstPhasellus.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/EstPhasellus.xls",
    hangiGun: "6-28-2022",
    avgArray: 5660,
    greaterAvgArray: 7604,
  },
  {
    filename: "UrnaUtTellus.mov",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/UrnaUtTellus.mov",
    hangiGun: "4-19-2022",
    avgArray: 2838,
    greaterAvgArray: 5445,
  },
  {
    filename: "Odio.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Odio.mp3",
    hangiGun: "2-11-2022",
    avgArray: 6762,
    greaterAvgArray: 9410,
  },
  {
    filename: "Quis.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Quis.avi",
    hangiGun: "3-4-2022",
    avgArray: 5477,
    greaterAvgArray: 2742,
  },
  {
    filename: "NullaFacilisi.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/NullaFacilisi.avi",
    hangiGun: "9-10-2022",
    avgArray: 7047,
    greaterAvgArray: 6875,
  },
  {
    filename: "IntegerAc.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/IntegerAc.ppt",
    hangiGun: "8-30-2022",
    avgArray: 8812,
    greaterAvgArray: 1564,
  },
  {
    filename: "Platea.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Platea.mp3",
    hangiGun: "4-13-2022",
    avgArray: 7919,
    greaterAvgArray: 3234,
  },
  {
    filename: "Cubilia.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Cubilia.avi",
    hangiGun: "3-23-2022",
    avgArray: 4692,
    greaterAvgArray: 4407,
  },
  {
    filename: "SedSagittisNam.tiff",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/SedSagittisNam.tiff",
    hangiGun: "2-10-2022",
    avgArray: 9978,
    greaterAvgArray: 254,
  },
  {
    filename: "SitAmet.mov",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/SitAmet.mov",
    hangiGun: "8-17-2022",
    avgArray: 5392,
    greaterAvgArray: 1607,
  },
  {
    filename: "Quisque.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Quisque.ppt",
    hangiGun: "10-29-2022",
    avgArray: 2243,
    greaterAvgArray: 2743,
  },
  {
    filename: "EuEst.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/EuEst.xls",
    hangiGun: "4-27-2022",
    avgArray: 184,
    greaterAvgArray: 1534,
  },
  {
    filename: "RisusDapibusAugue.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/RisusDapibusAugue.ppt",
    hangiGun: "9-23-2022",
    avgArray: 3514,
    greaterAvgArray: 1709,
  },
  {
    filename: "VelAccumsanTellus.tiff",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/VelAccumsanTellus.tiff",
    hangiGun: "1-21-2023",
    avgArray: 2172,
    greaterAvgArray: 645,
  },
  {
    filename: "Praesent.doc",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Praesent.doc",
    hangiGun: "10-17-2022",
    avgArray: 6572,
    greaterAvgArray: 3586,
  },
  {
    filename: "Vulputate.jpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Vulputate.jpeg",
    hangiGun: "10-21-2022",
    avgArray: 2142,
    greaterAvgArray: 2179,
  },
  {
    filename: "Turpis.png",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Turpis.png",
    hangiGun: "4-6-2022",
    avgArray: 8703,
    greaterAvgArray: 5568,
  },
  {
    filename: "LigulaSitAmet.tiff",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/LigulaSitAmet.tiff",
    hangiGun: "6-22-2022",
    avgArray: 7012,
    greaterAvgArray: 268,
  },
  {
    filename: "NamNulla.mov",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/NamNulla.mov",
    hangiGun: "1-20-2023",
    avgArray: 635,
    greaterAvgArray: 9349,
  },
  {
    filename: "DuisBibendumFelis.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/DuisBibendumFelis.mp3",
    hangiGun: "3-11-2022",
    avgArray: 8310,
    greaterAvgArray: 6964,
  },
  {
    filename: "Et.tiff",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Et.tiff",
    hangiGun: "6-20-2022",
    avgArray: 8440,
    greaterAvgArray: 9585,
  },
  {
    filename: "Quisque.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Quisque.mp3",
    hangiGun: "7-7-2022",
    avgArray: 7337,
    greaterAvgArray: 7954,
  },
  {
    filename: "VelitNec.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/VelitNec.mp3",
    hangiGun: "1-8-2023",
    avgArray: 1461,
    greaterAvgArray: 1140,
  },
  {
    filename: "NonMiInteger.pdf",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/NonMiInteger.pdf",
    hangiGun: "12-24-2022",
    avgArray: 9737,
    greaterAvgArray: 1925,
  },
  {
    filename: "Mauris.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Mauris.mp3",
    hangiGun: "12-8-2022",
    avgArray: 8434,
    greaterAvgArray: 6256,
  },
  {
    filename: "Etiam.tiff",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Etiam.tiff",
    hangiGun: "12-16-2022",
    avgArray: 9539,
    greaterAvgArray: 2518,
  },
  {
    filename: "Quam.tiff",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Quam.tiff",
    hangiGun: "6-9-2022",
    avgArray: 6004,
    greaterAvgArray: 274,
  },
  {
    filename: "DictumstMaecenas.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/DictumstMaecenas.mp3",
    hangiGun: "8-20-2022",
    avgArray: 273,
    greaterAvgArray: 8518,
  },
  {
    filename: "JustoAliquam.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/JustoAliquam.xls",
    hangiGun: "10-3-2022",
    avgArray: 2628,
    greaterAvgArray: 4167,
  },
  {
    filename: "DiamNequeVestibulum.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/DiamNequeVestibulum.avi",
    hangiGun: "5-21-2022",
    avgArray: 7281,
    greaterAvgArray: 4369,
  },
  {
    filename: "Quisque.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Quisque.mp3",
    hangiGun: "8-22-2022",
    avgArray: 1805,
    greaterAvgArray: 5294,
  },
  {
    filename: "Tristique.jpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Tristique.jpeg",
    hangiGun: "8-1-2022",
    avgArray: 9908,
    greaterAvgArray: 5329,
  },
  {
    filename: "Orci.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Orci.mp3",
    hangiGun: "5-28-2022",
    avgArray: 1255,
    greaterAvgArray: 1017,
  },
  {
    filename: "RidiculusMusVivamus.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/RidiculusMusVivamus.mp3",
    hangiGun: "8-9-2022",
    avgArray: 6507,
    greaterAvgArray: 9475,
  },
  {
    filename: "Curae.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Curae.xls",
    hangiGun: "1-14-2023",
    avgArray: 1776,
    greaterAvgArray: 9546,
  },
  {
    filename: "Turpis.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Turpis.xls",
    hangiGun: "1-7-2023",
    avgArray: 5777,
    greaterAvgArray: 1028,
  },
  {
    filename: "IntegerAliquetMassa.jpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/IntegerAliquetMassa.jpeg",
    hangiGun: "8-26-2022",
    avgArray: 3492,
    greaterAvgArray: 4395,
  },
  {
    filename: "Diam.tiff",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Diam.tiff",
    hangiGun: "1-13-2023",
    avgArray: 6277,
    greaterAvgArray: 639,
  },
  {
    filename: "SedVel.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/SedVel.ppt",
    hangiGun: "11-23-2022",
    avgArray: 5433,
    greaterAvgArray: 3316,
  },
  {
    filename: "LaciniaAeneanSit.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/LaciniaAeneanSit.ppt",
    hangiGun: "7-29-2022",
    avgArray: 5043,
    greaterAvgArray: 8778,
  },
  {
    filename: "LeoRhoncusSed.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/LeoRhoncusSed.avi",
    hangiGun: "6-26-2022",
    avgArray: 7506,
    greaterAvgArray: 8542,
  },
  {
    filename: "Bibendum.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Bibendum.xls",
    hangiGun: "7-23-2022",
    avgArray: 8427,
    greaterAvgArray: 6835,
  },
  {
    filename: "NequeSapienPlacerat.tiff",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/NequeSapienPlacerat.tiff",
    hangiGun: "11-10-2022",
    avgArray: 1184,
    greaterAvgArray: 1960,
  },
  {
    filename: "Lorem.gif",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Lorem.gif",
    hangiGun: "4-12-2022",
    avgArray: 7720,
    greaterAvgArray: 6545,
  },
  {
    filename: "SitAmetEleifend.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/SitAmetEleifend.ppt",
    hangiGun: "7-1-2022",
    avgArray: 8850,
    greaterAvgArray: 4094,
  },
  {
    filename: "ASuscipitNulla.tiff",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/ASuscipitNulla.tiff",
    hangiGun: "8-16-2022",
    avgArray: 2299,
    greaterAvgArray: 7905,
  },
  {
    filename: "SedLacus.mpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/SedLacus.mpeg",
    hangiGun: "12-16-2022",
    avgArray: 5549,
    greaterAvgArray: 6806,
  },
  {
    filename: "Facilisi.doc",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Facilisi.doc",
    hangiGun: "5-21-2022",
    avgArray: 396,
    greaterAvgArray: 1110,
  },
  {
    filename: "CrasInPurus.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/CrasInPurus.avi",
    hangiGun: "8-31-2022",
    avgArray: 1082,
    greaterAvgArray: 4198,
  },
  {
    filename: "NullaNuncPurus.png",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/NullaNuncPurus.png",
    hangiGun: "8-14-2022",
    avgArray: 3344,
    greaterAvgArray: 2527,
  },
  {
    filename: "Aenean.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Aenean.avi",
    hangiGun: "6-16-2022",
    avgArray: 5941,
    greaterAvgArray: 8504,
  },
  {
    filename: "Ut.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Ut.mp3",
    hangiGun: "11-6-2022",
    avgArray: 3455,
    greaterAvgArray: 4335,
  },
  {
    filename: "Ut.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Ut.mp3",
    hangiGun: "1-25-2023",
    avgArray: 7398,
    greaterAvgArray: 9754,
  },
  {
    filename: "SapienArcu.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/SapienArcu.xls",
    hangiGun: "12-5-2022",
    avgArray: 6850,
    greaterAvgArray: 637,
  },
  {
    filename: "MattisPulvinar.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/MattisPulvinar.mp3",
    hangiGun: "2-10-2022",
    avgArray: 7084,
    greaterAvgArray: 597,
  },
  {
    filename: "EtMagnis.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/EtMagnis.avi",
    hangiGun: "8-8-2022",
    avgArray: 1722,
    greaterAvgArray: 4470,
  },
  {
    filename: "Vivamus.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Vivamus.mp3",
    hangiGun: "11-6-2022",
    avgArray: 7444,
    greaterAvgArray: 2332,
  },
  {
    filename: "DapibusAugueVel.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/DapibusAugueVel.ppt",
    hangiGun: "6-15-2022",
    avgArray: 8991,
    greaterAvgArray: 1865,
  },
  {
    filename: "Consequat.png",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Consequat.png",
    hangiGun: "11-25-2022",
    avgArray: 324,
    greaterAvgArray: 8392,
  },
  {
    filename: "PorttitorIdConsequat.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/PorttitorIdConsequat.avi",
    hangiGun: "4-2-2022",
    avgArray: 5439,
    greaterAvgArray: 4068,
  },
  {
    filename: "Odio.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Odio.mp3",
    hangiGun: "1-2-2023",
    avgArray: 7512,
    greaterAvgArray: 6402,
  },
  {
    filename: "Vulputate.jpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Vulputate.jpeg",
    hangiGun: "5-15-2022",
    avgArray: 2419,
    greaterAvgArray: 9921,
  },
  {
    filename: "ScelerisqueMauris.mov",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/ScelerisqueMauris.mov",
    hangiGun: "3-24-2022",
    avgArray: 5155,
    greaterAvgArray: 4143,
  },
  {
    filename: "AeneanAuctorGravida.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/AeneanAuctorGravida.mp3",
    hangiGun: "5-21-2022",
    avgArray: 5377,
    greaterAvgArray: 4528,
  },
  {
    filename: "AdipiscingMolestie.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/AdipiscingMolestie.ppt",
    hangiGun: "11-26-2022",
    avgArray: 8871,
    greaterAvgArray: 8865,
  },
  {
    filename: "Convallis.jpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Convallis.jpeg",
    hangiGun: "8-9-2022",
    avgArray: 1043,
    greaterAvgArray: 8692,
  },
  {
    filename: "Ultrices.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Ultrices.mp3",
    hangiGun: "8-22-2022",
    avgArray: 473,
    greaterAvgArray: 3238,
  },
  {
    filename: "EtUltrices.tiff",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/EtUltrices.tiff",
    hangiGun: "10-9-2022",
    avgArray: 6876,
    greaterAvgArray: 4498,
  },
  {
    filename: "MorbiNonQuam.png",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/MorbiNonQuam.png",
    hangiGun: "5-23-2022",
    avgArray: 5019,
    greaterAvgArray: 5908,
  },
  {
    filename: "Vestibulum.pdf",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Vestibulum.pdf",
    hangiGun: "11-1-2022",
    avgArray: 1353,
    greaterAvgArray: 5340,
  },
  {
    filename: "NecCondimentumNeque.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/NecCondimentumNeque.xls",
    hangiGun: "4-12-2022",
    avgArray: 4171,
    greaterAvgArray: 1144,
  },
  {
    filename: "Volutpat.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Volutpat.mp3",
    hangiGun: "5-10-2022",
    avgArray: 6309,
    greaterAvgArray: 9610,
  },
  {
    filename: "Mi.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Mi.ppt",
    hangiGun: "2-17-2022",
    avgArray: 8763,
    greaterAvgArray: 5574,
  },
  {
    filename: "MorbiVel.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/MorbiVel.ppt",
    hangiGun: "8-12-2022",
    avgArray: 7347,
    greaterAvgArray: 1786,
  },
  {
    filename: "QuamNecDui.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/QuamNecDui.ppt",
    hangiGun: "1-19-2023",
    avgArray: 1216,
    greaterAvgArray: 1116,
  },
  {
    filename: "In.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/In.xls",
    hangiGun: "8-23-2022",
    avgArray: 4842,
    greaterAvgArray: 1790,
  },
  {
    filename: "JustoMorbiUt.doc",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/JustoMorbiUt.doc",
    hangiGun: "2-15-2022",
    avgArray: 6182,
    greaterAvgArray: 9389,
  },
  {
    filename: "FaucibusOrciLuctus.tiff",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/FaucibusOrciLuctus.tiff",
    hangiGun: "9-27-2022",
    avgArray: 3218,
    greaterAvgArray: 6717,
  },
  {
    filename: "VelitDonec.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/VelitDonec.ppt",
    hangiGun: "2-24-2022",
    avgArray: 2737,
    greaterAvgArray: 802,
  },
  {
    filename: "Mauris.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Mauris.xls",
    hangiGun: "5-20-2022",
    avgArray: 352,
    greaterAvgArray: 4852,
  },
  {
    filename: "Varius.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Varius.xls",
    hangiGun: "12-26-2022",
    avgArray: 2492,
    greaterAvgArray: 7975,
  },
  {
    filename: "Etiam.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Etiam.avi",
    hangiGun: "1-10-2023",
    avgArray: 5505,
    greaterAvgArray: 326,
  },
  {
    filename: "ConvallisTortorRisus.jpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/ConvallisTortorRisus.jpeg",
    hangiGun: "2-18-2022",
    avgArray: 7975,
    greaterAvgArray: 8196,
  },
  {
    filename: "Vitae.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Vitae.mp3",
    hangiGun: "2-13-2022",
    avgArray: 4719,
    greaterAvgArray: 5915,
  },
  {
    filename: "InImperdiet.pdf",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/InImperdiet.pdf",
    hangiGun: "6-10-2022",
    avgArray: 7099,
    greaterAvgArray: 5389,
  },
  {
    filename: "Nulla.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Nulla.ppt",
    hangiGun: "5-20-2022",
    avgArray: 9730,
    greaterAvgArray: 4135,
  },
  {
    filename: "LoremIpsum.jpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/LoremIpsum.jpeg",
    hangiGun: "7-17-2022",
    avgArray: 7848,
    greaterAvgArray: 1871,
  },
  {
    filename: "VelitVivamusVel.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/VelitVivamusVel.ppt",
    hangiGun: "6-2-2022",
    avgArray: 2567,
    greaterAvgArray: 8221,
  },
  {
    filename: "FelisUt.pdf",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/FelisUt.pdf",
    hangiGun: "7-12-2022",
    avgArray: 4220,
    greaterAvgArray: 7964,
  },
  {
    filename: "QuisLiberoNullam.pdf",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/QuisLiberoNullam.pdf",
    hangiGun: "3-5-2022",
    avgArray: 1948,
    greaterAvgArray: 3544,
  },
  {
    filename: "AtLorem.tiff",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/AtLorem.tiff",
    hangiGun: "1-1-2023",
    avgArray: 3345,
    greaterAvgArray: 8611,
  },
  {
    filename: "PosuereNonummyInteger.doc",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/PosuereNonummyInteger.doc",
    hangiGun: "1-27-2023",
    avgArray: 7207,
    greaterAvgArray: 9548,
  },
  {
    filename: "FuscePosuereFelis.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/FuscePosuereFelis.avi",
    hangiGun: "12-31-2022",
    avgArray: 8789,
    greaterAvgArray: 156,
  },
  {
    filename: "Nulla.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Nulla.xls",
    hangiGun: "5-18-2022",
    avgArray: 5930,
    greaterAvgArray: 1747,
  },
  {
    filename: "Ipsum.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Ipsum.avi",
    hangiGun: "5-17-2022",
    avgArray: 7496,
    greaterAvgArray: 4384,
  },
  {
    filename: "InEleifend.jpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/InEleifend.jpeg",
    hangiGun: "2-7-2023",
    avgArray: 6748,
    greaterAvgArray: 4311,
  },
  {
    filename: "SapienIaculis.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/SapienIaculis.ppt",
    hangiGun: "6-14-2022",
    avgArray: 8549,
    greaterAvgArray: 1878,
  },
  {
    filename: "Quam.txt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Quam.txt",
    hangiGun: "8-22-2022",
    avgArray: 9047,
    greaterAvgArray: 9795,
  },
  {
    filename: "FaucibusOrciLuctus.tiff",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/FaucibusOrciLuctus.tiff",
    hangiGun: "10-15-2022",
    avgArray: 7278,
    greaterAvgArray: 6752,
  },
  {
    filename: "Adipiscing.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Adipiscing.avi",
    hangiGun: "10-23-2022",
    avgArray: 5245,
    greaterAvgArray: 2813,
  },
  {
    filename: "TinciduntIn.mpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/TinciduntIn.mpeg",
    hangiGun: "7-26-2022",
    avgArray: 5482,
    greaterAvgArray: 9328,
  },
  {
    filename: "Mauris.gif",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Mauris.gif",
    hangiGun: "1-4-2023",
    avgArray: 14,
    greaterAvgArray: 2655,
  },
  {
    filename: "OdioPorttitorId.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/OdioPorttitorId.ppt",
    hangiGun: "1-12-2023",
    avgArray: 7407,
    greaterAvgArray: 3269,
  },
  {
    filename: "NonPretiumQuis.jpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/NonPretiumQuis.jpeg",
    hangiGun: "4-28-2022",
    avgArray: 4144,
    greaterAvgArray: 1147,
  },
  {
    filename: "CuraeNullaDapibus.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/CuraeNullaDapibus.xls",
    hangiGun: "4-9-2022",
    avgArray: 9804,
    greaterAvgArray: 4960,
  },
  {
    filename: "EratVolutpatIn.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/EratVolutpatIn.avi",
    hangiGun: "12-7-2022",
    avgArray: 1969,
    greaterAvgArray: 760,
  },
  {
    filename: "Neque.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Neque.xls",
    hangiGun: "6-11-2022",
    avgArray: 8409,
    greaterAvgArray: 2795,
  },
  {
    filename: "Convallis.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Convallis.ppt",
    hangiGun: "8-22-2022",
    avgArray: 7263,
    greaterAvgArray: 4758,
  },
  {
    filename: "LigulaNecSem.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/LigulaNecSem.ppt",
    hangiGun: "3-29-2022",
    avgArray: 6624,
    greaterAvgArray: 610,
  },
  {
    filename: "InSapienIaculis.jpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/InSapienIaculis.jpeg",
    hangiGun: "6-7-2022",
    avgArray: 5051,
    greaterAvgArray: 130,
  },
  {
    filename: "VestibulumAnteIpsum.tiff",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/VestibulumAnteIpsum.tiff",
    hangiGun: "10-14-2022",
    avgArray: 7823,
    greaterAvgArray: 8220,
  },
  {
    filename: "AliquetAtFeugiat.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/AliquetAtFeugiat.avi",
    hangiGun: "9-11-2022",
    avgArray: 6393,
    greaterAvgArray: 8939,
  },
  {
    filename: "LeoMaecenasPulvinar.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/LeoMaecenasPulvinar.ppt",
    hangiGun: "1-29-2023",
    avgArray: 6427,
    greaterAvgArray: 2673,
  },
  {
    filename: "NisiVenenatis.mpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/NisiVenenatis.mpeg",
    hangiGun: "8-15-2022",
    avgArray: 7032,
    greaterAvgArray: 642,
  },
  {
    filename: "NamCongue.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/NamCongue.mp3",
    hangiGun: "10-23-2022",
    avgArray: 107,
    greaterAvgArray: 9149,
  },
  {
    filename: "ElementumPellentesqueQuisque.ppt",
    dosyaAdiniBul:
      "C:/Users/johnsmith/Documents/ElementumPellentesqueQuisque.ppt",
    hangiGun: "6-15-2022",
    avgArray: 6076,
    greaterAvgArray: 5288,
  },
  {
    filename: "RhoncusAliquamLacus.jpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/RhoncusAliquamLacus.jpeg",
    hangiGun: "1-13-2023",
    avgArray: 3375,
    greaterAvgArray: 5794,
  },
  {
    filename: "NibhIn.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/NibhIn.ppt",
    hangiGun: "6-9-2022",
    avgArray: 1583,
    greaterAvgArray: 1887,
  },
  {
    filename: "FelisFuscePosuere.tiff",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/FelisFuscePosuere.tiff",
    hangiGun: "2-27-2022",
    avgArray: 7692,
    greaterAvgArray: 8,
  },
  {
    filename: "NullaEget.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/NullaEget.avi",
    hangiGun: "6-23-2022",
    avgArray: 2341,
    greaterAvgArray: 896,
  },
  {
    filename: "MolestieSed.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/MolestieSed.xls",
    hangiGun: "3-30-2022",
    avgArray: 9590,
    greaterAvgArray: 6479,
  },
  {
    filename: "UtErat.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/UtErat.avi",
    hangiGun: "10-8-2022",
    avgArray: 6028,
    greaterAvgArray: 1086,
  },
  {
    filename: "OrnareImperdietSapien.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/OrnareImperdietSapien.mp3",
    hangiGun: "3-24-2022",
    avgArray: 7573,
    greaterAvgArray: 2237,
  },
  {
    filename: "Eu.gif",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Eu.gif",
    hangiGun: "6-8-2022",
    avgArray: 7073,
    greaterAvgArray: 4591,
  },
  {
    filename: "Nascetur.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Nascetur.mp3",
    hangiGun: "3-23-2022",
    avgArray: 3643,
    greaterAvgArray: 5910,
  },
  {
    filename: "Auctor.doc",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Auctor.doc",
    hangiGun: "3-18-2022",
    avgArray: 213,
    greaterAvgArray: 9894,
  },
  {
    filename: "JustoMorbiUt.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/JustoMorbiUt.mp3",
    hangiGun: "6-15-2022",
    avgArray: 3267,
    greaterAvgArray: 4184,
  },
  {
    filename: "SapienDignissimVestibulum.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/SapienDignissimVestibulum.ppt",
    hangiGun: "11-4-2022",
    avgArray: 6356,
    greaterAvgArray: 7546,
  },
  {
    filename: "MaecenasUtMassa.tiff",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/MaecenasUtMassa.tiff",
    hangiGun: "12-20-2022",
    avgArray: 3330,
    greaterAvgArray: 3777,
  },
  {
    filename: "VolutpatEleifendDonec.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/VolutpatEleifendDonec.mp3",
    hangiGun: "11-24-2022",
    avgArray: 9265,
    greaterAvgArray: 4421,
  },
  {
    filename: "TristiqueIn.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/TristiqueIn.xls",
    hangiGun: "11-4-2022",
    avgArray: 4089,
    greaterAvgArray: 1278,
  },
  {
    filename: "IdNullaUltrices.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/IdNullaUltrices.avi",
    hangiGun: "11-7-2022",
    avgArray: 2999,
    greaterAvgArray: 9463,
  },
  {
    filename: "Orci.png",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Orci.png",
    hangiGun: "2-17-2022",
    avgArray: 8731,
    greaterAvgArray: 4960,
  },
  {
    filename: "EgetEros.tiff",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/EgetEros.tiff",
    hangiGun: "4-13-2022",
    avgArray: 4798,
    greaterAvgArray: 8459,
  },
  {
    filename: "VestibulumVestibulum.doc",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/VestibulumVestibulum.doc",
    hangiGun: "3-25-2022",
    avgArray: 8101,
    greaterAvgArray: 9814,
  },
  {
    filename: "TortorRisusDapibus.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/TortorRisusDapibus.mp3",
    hangiGun: "11-9-2022",
    avgArray: 1545,
    greaterAvgArray: 8694,
  },
  {
    filename: "Adipiscing.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Adipiscing.ppt",
    hangiGun: "1-12-2023",
    avgArray: 91,
    greaterAvgArray: 6606,
  },
  {
    filename: "Potenti.mpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Potenti.mpeg",
    hangiGun: "5-12-2022",
    avgArray: 9398,
    greaterAvgArray: 9615,
  },
  {
    filename: "NullaSedVel.doc",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/NullaSedVel.doc",
    hangiGun: "8-6-2022",
    avgArray: 6292,
    greaterAvgArray: 6514,
  },
  {
    filename: "Sit.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Sit.mp3",
    hangiGun: "3-26-2022",
    avgArray: 2966,
    greaterAvgArray: 8483,
  },
  {
    filename: "NequeLibero.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/NequeLibero.xls",
    hangiGun: "11-19-2022",
    avgArray: 925,
    greaterAvgArray: 7122,
  },
  {
    filename: "LiberoNullamSit.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/LiberoNullamSit.ppt",
    hangiGun: "6-20-2022",
    avgArray: 6917,
    greaterAvgArray: 5093,
  },
  {
    filename: "NequeDuis.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/NequeDuis.mp3",
    hangiGun: "9-21-2022",
    avgArray: 5996,
    greaterAvgArray: 6511,
  },
  {
    filename: "VitaeNisl.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/VitaeNisl.mp3",
    hangiGun: "4-25-2022",
    avgArray: 8787,
    greaterAvgArray: 3601,
  },
  {
    filename: "ElementumEuInterdum.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/ElementumEuInterdum.xls",
    hangiGun: "8-17-2022",
    avgArray: 2880,
    greaterAvgArray: 8824,
  },
  {
    filename: "MassaVolutpat.gif",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/MassaVolutpat.gif",
    hangiGun: "8-5-2022",
    avgArray: 2218,
    greaterAvgArray: 4924,
  },
  {
    filename: "Ultrices.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Ultrices.ppt",
    hangiGun: "7-13-2022",
    avgArray: 4997,
    greaterAvgArray: 4236,
  },
  {
    filename: "LobortisLigulaSit.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/LobortisLigulaSit.mp3",
    hangiGun: "8-19-2022",
    avgArray: 4325,
    greaterAvgArray: 5006,
  },
  {
    filename: "SitAmet.tiff",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/SitAmet.tiff",
    hangiGun: "5-24-2022",
    avgArray: 4120,
    greaterAvgArray: 6456,
  },
  {
    filename: "Viverra.jpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Viverra.jpeg",
    hangiGun: "1-17-2023",
    avgArray: 6109,
    greaterAvgArray: 6754,
  },
  {
    filename: "Non.gif",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Non.gif",
    hangiGun: "8-28-2022",
    avgArray: 2117,
    greaterAvgArray: 163,
  },
  {
    filename: "UtDolor.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/UtDolor.avi",
    hangiGun: "7-26-2022",
    avgArray: 3013,
    greaterAvgArray: 6697,
  },
  {
    filename: "RidiculusMusEtiam.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/RidiculusMusEtiam.avi",
    hangiGun: "11-6-2022",
    avgArray: 3076,
    greaterAvgArray: 6072,
  },
  {
    filename: "VestibulumEget.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/VestibulumEget.ppt",
    hangiGun: "9-29-2022",
    avgArray: 7612,
    greaterAvgArray: 9153,
  },
  {
    filename: "JustoNecCondimentum.mpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/JustoNecCondimentum.mpeg",
    hangiGun: "5-26-2022",
    avgArray: 1437,
    greaterAvgArray: 7649,
  },
  {
    filename: "Venenatis.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Venenatis.mp3",
    hangiGun: "9-9-2022",
    avgArray: 804,
    greaterAvgArray: 6288,
  },
  {
    filename: "Sit.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Sit.ppt",
    hangiGun: "1-7-2023",
    avgArray: 9353,
    greaterAvgArray: 4679,
  },
  {
    filename: "Porttitor.tiff",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Porttitor.tiff",
    hangiGun: "6-6-2022",
    avgArray: 9606,
    greaterAvgArray: 5831,
  },
  {
    filename: "DuisBibendumMorbi.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/DuisBibendumMorbi.avi",
    hangiGun: "6-24-2022",
    avgArray: 3114,
    greaterAvgArray: 4058,
  },
  {
    filename: "DuiProinLeo.png",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/DuiProinLeo.png",
    hangiGun: "5-12-2022",
    avgArray: 6509,
    greaterAvgArray: 9270,
  },
  {
    filename: "LacusMorbi.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/LacusMorbi.xls",
    hangiGun: "10-2-2022",
    avgArray: 6691,
    greaterAvgArray: 8673,
  },
  {
    filename: "Ligula.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Ligula.mp3",
    hangiGun: "8-19-2022",
    avgArray: 3362,
    greaterAvgArray: 8193,
  },
  {
    filename: "IpsumPrimis.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/IpsumPrimis.ppt",
    hangiGun: "3-14-2022",
    avgArray: 3877,
    greaterAvgArray: 5963,
  },
  {
    filename: "PrimisIn.mpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/PrimisIn.mpeg",
    hangiGun: "12-26-2022",
    avgArray: 8106,
    greaterAvgArray: 9509,
  },
  {
    filename: "InterdumIn.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/InterdumIn.xls",
    hangiGun: "2-22-2022",
    avgArray: 5857,
    greaterAvgArray: 616,
  },
  {
    filename: "VulputateLuctusCum.doc",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/VulputateLuctusCum.doc",
    hangiGun: "10-3-2022",
    avgArray: 6622,
    greaterAvgArray: 9741,
  },
  {
    filename: "LectusSuspendisse.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/LectusSuspendisse.xls",
    hangiGun: "12-19-2022",
    avgArray: 3437,
    greaterAvgArray: 1619,
  },
  {
    filename: "DiamVitae.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/DiamVitae.ppt",
    hangiGun: "9-30-2022",
    avgArray: 1324,
    greaterAvgArray: 1266,
  },
  {
    filename: "OrciLuctusEt.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/OrciLuctusEt.mp3",
    hangiGun: "8-27-2022",
    avgArray: 4734,
    greaterAvgArray: 1194,
  },
  {
    filename: "ErosVestibulumAc.pdf",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/ErosVestibulumAc.pdf",
    hangiGun: "10-6-2022",
    avgArray: 9341,
    greaterAvgArray: 5861,
  },
  {
    filename: "JustoSollicitudin.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/JustoSollicitudin.mp3",
    hangiGun: "1-13-2023",
    avgArray: 960,
    greaterAvgArray: 4358,
  },
  {
    filename: "LoremIpsumDolor.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/LoremIpsumDolor.avi",
    hangiGun: "4-1-2022",
    avgArray: 6947,
    greaterAvgArray: 1532,
  },
  {
    filename: "FelisEu.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/FelisEu.xls",
    hangiGun: "1-8-2023",
    avgArray: 6943,
    greaterAvgArray: 9518,
  },
  {
    filename: "Risus.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Risus.xls",
    hangiGun: "5-11-2022",
    avgArray: 3052,
    greaterAvgArray: 3283,
  },
  {
    filename: "Nullam.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Nullam.mp3",
    hangiGun: "1-7-2023",
    avgArray: 8396,
    greaterAvgArray: 1512,
  },
  {
    filename: "Volutpat.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Volutpat.ppt",
    hangiGun: "8-16-2022",
    avgArray: 5303,
    greaterAvgArray: 9805,
  },
  {
    filename: "Vitae.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Vitae.xls",
    hangiGun: "2-17-2022",
    avgArray: 2898,
    greaterAvgArray: 3334,
  },
  {
    filename: "Amet.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Amet.xls",
    hangiGun: "1-21-2023",
    avgArray: 2457,
    greaterAvgArray: 506,
  },
  {
    filename: "VelAugue.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/VelAugue.avi",
    hangiGun: "5-11-2022",
    avgArray: 9309,
    greaterAvgArray: 7028,
  },
  {
    filename: "Condimentum.jpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Condimentum.jpeg",
    hangiGun: "5-17-2022",
    avgArray: 4169,
    greaterAvgArray: 15,
  },
  {
    filename: "NullaUltricesAliquet.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/NullaUltricesAliquet.xls",
    hangiGun: "3-9-2022",
    avgArray: 7898,
    greaterAvgArray: 9085,
  },
  {
    filename: "DonecUt.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/DonecUt.avi",
    hangiGun: "1-31-2023",
    avgArray: 5378,
    greaterAvgArray: 7382,
  },
  {
    filename: "MagnaBibendumImperdiet.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/MagnaBibendumImperdiet.mp3",
    hangiGun: "4-24-2022",
    avgArray: 5080,
    greaterAvgArray: 1466,
  },
  {
    filename: "Turpis.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Turpis.avi",
    hangiGun: "10-14-2022",
    avgArray: 7424,
    greaterAvgArray: 7211,
  },
  {
    filename: "Turpis.png",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Turpis.png",
    hangiGun: "2-7-2023",
    avgArray: 6756,
    greaterAvgArray: 1211,
  },
  {
    filename: "Nullam.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Nullam.ppt",
    hangiGun: "6-12-2022",
    avgArray: 8661,
    greaterAvgArray: 1582,
  },
  {
    filename: "VitaeMattis.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/VitaeMattis.mp3",
    hangiGun: "3-22-2022",
    avgArray: 2514,
    greaterAvgArray: 3102,
  },
  {
    filename: "MaurisSitAmet.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/MaurisSitAmet.avi",
    hangiGun: "9-8-2022",
    avgArray: 5232,
    greaterAvgArray: 2147,
  },
  {
    filename: "Sed.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Sed.ppt",
    hangiGun: "1-29-2023",
    avgArray: 5634,
    greaterAvgArray: 1395,
  },
  {
    filename: "SedTinciduntEu.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/SedTinciduntEu.xls",
    hangiGun: "4-29-2022",
    avgArray: 9007,
    greaterAvgArray: 7208,
  },
  {
    filename: "VenenatisNon.pdf",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/VenenatisNon.pdf",
    hangiGun: "1-13-2023",
    avgArray: 815,
    greaterAvgArray: 8864,
  },
  {
    filename: "DiamNamTristique.mpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/DiamNamTristique.mpeg",
    hangiGun: "5-16-2022",
    avgArray: 3016,
    greaterAvgArray: 6392,
  },
  {
    filename: "SagittisSapienCum.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/SagittisSapienCum.mp3",
    hangiGun: "11-27-2022",
    avgArray: 3018,
    greaterAvgArray: 8722,
  },
  {
    filename: "NuncRhoncusDui.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/NuncRhoncusDui.ppt",
    hangiGun: "11-9-2022",
    avgArray: 5634,
    greaterAvgArray: 7971,
  },
  {
    filename: "NasceturRidiculusMus.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/NasceturRidiculusMus.avi",
    hangiGun: "7-26-2022",
    avgArray: 6998,
    greaterAvgArray: 8635,
  },
  {
    filename: "Purus.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Purus.xls",
    hangiGun: "3-29-2022",
    avgArray: 5649,
    greaterAvgArray: 193,
  },
  {
    filename: "FringillaRhoncusMauris.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/FringillaRhoncusMauris.avi",
    hangiGun: "2-26-2022",
    avgArray: 5521,
    greaterAvgArray: 6482,
  },
  {
    filename: "PellentesqueAt.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/PellentesqueAt.avi",
    hangiGun: "1-17-2023",
    avgArray: 199,
    greaterAvgArray: 3362,
  },
  {
    filename: "VelDapibusAt.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/VelDapibusAt.ppt",
    hangiGun: "11-6-2022",
    avgArray: 3715,
    greaterAvgArray: 4607,
  },
  {
    filename: "ProinLeo.pdf",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/ProinLeo.pdf",
    hangiGun: "12-13-2022",
    avgArray: 5077,
    greaterAvgArray: 8464,
  },
  {
    filename: "VelSemSed.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/VelSemSed.mp3",
    hangiGun: "2-16-2022",
    avgArray: 7981,
    greaterAvgArray: 7472,
  },
  {
    filename: "Maecenas.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Maecenas.ppt",
    hangiGun: "5-29-2022",
    avgArray: 1722,
    greaterAvgArray: 5956,
  },
  {
    filename: "SapienVariusUt.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/SapienVariusUt.xls",
    hangiGun: "8-20-2022",
    avgArray: 1487,
    greaterAvgArray: 6066,
  },
  {
    filename: "Quisque.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Quisque.xls",
    hangiGun: "12-31-2022",
    avgArray: 3606,
    greaterAvgArray: 6119,
  },
  {
    filename: "ImperdietSapienUrna.png",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/ImperdietSapienUrna.png",
    hangiGun: "3-19-2022",
    avgArray: 3515,
    greaterAvgArray: 9848,
  },
  {
    filename: "TurpisSed.gif",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/TurpisSed.gif",
    hangiGun: "11-26-2022",
    avgArray: 2048,
    greaterAvgArray: 6401,
  },
  {
    filename: "DonecPosuereMetus.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/DonecPosuereMetus.mp3",
    hangiGun: "5-26-2022",
    avgArray: 8001,
    greaterAvgArray: 3261,
  },
  {
    filename: "EgetCongueEget.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/EgetCongueEget.xls",
    hangiGun: "6-8-2022",
    avgArray: 7028,
    greaterAvgArray: 6321,
  },
  {
    filename: "InHac.jpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/InHac.jpeg",
    hangiGun: "12-1-2022",
    avgArray: 774,
    greaterAvgArray: 7242,
  },
  {
    filename: "Ac.png",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Ac.png",
    hangiGun: "12-26-2022",
    avgArray: 8266,
    greaterAvgArray: 177,
  },
  {
    filename: "NuncNisl.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/NuncNisl.mp3",
    hangiGun: "10-18-2022",
    avgArray: 5261,
    greaterAvgArray: 2534,
  },
  {
    filename: "SemperPortaVolutpat.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/SemperPortaVolutpat.avi",
    hangiGun: "1-26-2023",
    avgArray: 5194,
    greaterAvgArray: 5450,
  },
  {
    filename: "Eget.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Eget.avi",
    hangiGun: "5-10-2022",
    avgArray: 4590,
    greaterAvgArray: 4746,
  },
  {
    filename: "IpsumDolorSit.mov",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/IpsumDolorSit.mov",
    hangiGun: "5-4-2022",
    avgArray: 491,
    greaterAvgArray: 8316,
  },
  {
    filename: "EnimBlandit.txt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/EnimBlandit.txt",
    hangiGun: "3-12-2022",
    avgArray: 4909,
    greaterAvgArray: 5842,
  },
  {
    filename: "HacHabitassePlatea.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/HacHabitassePlatea.ppt",
    hangiGun: "6-29-2022",
    avgArray: 4600,
    greaterAvgArray: 5732,
  },
  {
    filename: "LoremIpsumDolor.tiff",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/LoremIpsumDolor.tiff",
    hangiGun: "3-30-2022",
    avgArray: 4428,
    greaterAvgArray: 1965,
  },
  {
    filename: "FermentumJustoNec.jpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/FermentumJustoNec.jpeg",
    hangiGun: "8-2-2022",
    avgArray: 104,
    greaterAvgArray: 330,
  },
  {
    filename: "EratTortorSollicitudin.mov",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/EratTortorSollicitudin.mov",
    hangiGun: "10-14-2022",
    avgArray: 7937,
    greaterAvgArray: 372,
  },
  {
    filename: "CurabiturIn.tiff",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/CurabiturIn.tiff",
    hangiGun: "1-12-2023",
    avgArray: 2002,
    greaterAvgArray: 1554,
  },
  {
    filename: "Erat.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Erat.mp3",
    hangiGun: "5-3-2022",
    avgArray: 9122,
    greaterAvgArray: 9559,
  },
  {
    filename: "InterdumIn.tiff",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/InterdumIn.tiff",
    hangiGun: "1-2-2023",
    avgArray: 1316,
    greaterAvgArray: 6905,
  },
  {
    filename: "FeugiatEtEros.tiff",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/FeugiatEtEros.tiff",
    hangiGun: "12-23-2022",
    avgArray: 9894,
    greaterAvgArray: 2825,
  },
  {
    filename: "QuamSollicitudinVitae.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/QuamSollicitudinVitae.xls",
    hangiGun: "11-17-2022",
    avgArray: 5454,
    greaterAvgArray: 2021,
  },
  {
    filename: "NullamOrci.gif",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/NullamOrci.gif",
    hangiGun: "3-25-2022",
    avgArray: 4619,
    greaterAvgArray: 3841,
  },
  {
    filename: "Venenatis.doc",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Venenatis.doc",
    hangiGun: "10-10-2022",
    avgArray: 5656,
    greaterAvgArray: 7387,
  },
  {
    filename: "Nunc.mpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Nunc.mpeg",
    hangiGun: "6-5-2022",
    avgArray: 4848,
    greaterAvgArray: 1358,
  },
  {
    filename: "LaciniaEratVestibulum.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/LaciniaEratVestibulum.xls",
    hangiGun: "3-27-2022",
    avgArray: 6214,
    greaterAvgArray: 675,
  },
  {
    filename: "RisusSemperPorta.jpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/RisusSemperPorta.jpeg",
    hangiGun: "5-25-2022",
    avgArray: 8923,
    greaterAvgArray: 3118,
  },
  {
    filename: "EtiamVelAugue.txt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/EtiamVelAugue.txt",
    hangiGun: "9-22-2022",
    avgArray: 6262,
    greaterAvgArray: 7305,
  },
  {
    filename: "Nibh.pdf",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Nibh.pdf",
    hangiGun: "11-7-2022",
    avgArray: 5821,
    greaterAvgArray: 2013,
  },
  {
    filename: "Luctus.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Luctus.avi",
    hangiGun: "9-29-2022",
    avgArray: 9351,
    greaterAvgArray: 774,
  },
  {
    filename: "PorttitorLorem.mov",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/PorttitorLorem.mov",
    hangiGun: "10-20-2022",
    avgArray: 8736,
    greaterAvgArray: 1508,
  },
  {
    filename: "Maecenas.png",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Maecenas.png",
    hangiGun: "4-18-2022",
    avgArray: 621,
    greaterAvgArray: 4538,
  },
  {
    filename: "Etiam.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Etiam.xls",
    hangiGun: "1-9-2023",
    avgArray: 1992,
    greaterAvgArray: 6143,
  },
  {
    filename: "TortorSollicitudinMi.tiff",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/TortorSollicitudinMi.tiff",
    hangiGun: "9-8-2022",
    avgArray: 683,
    greaterAvgArray: 8248,
  },
  {
    filename: "Iaculis.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Iaculis.mp3",
    hangiGun: "10-3-2022",
    avgArray: 605,
    greaterAvgArray: 7219,
  },
  {
    filename: "Dictumst.png",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Dictumst.png",
    hangiGun: "1-11-2023",
    avgArray: 1085,
    greaterAvgArray: 5503,
  },
  {
    filename: "EgetRutrumAt.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/EgetRutrumAt.ppt",
    hangiGun: "1-26-2023",
    avgArray: 4819,
    greaterAvgArray: 851,
  },
  {
    filename: "AeneanLectus.txt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/AeneanLectus.txt",
    hangiGun: "8-20-2022",
    avgArray: 8886,
    greaterAvgArray: 2440,
  },
  {
    filename: "NamCongueRisus.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/NamCongueRisus.mp3",
    hangiGun: "4-16-2022",
    avgArray: 2358,
    greaterAvgArray: 6878,
  },
  {
    filename: "Nulla.txt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Nulla.txt",
    hangiGun: "12-13-2022",
    avgArray: 4977,
    greaterAvgArray: 7217,
  },
  {
    filename: "Eleifend.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Eleifend.xls",
    hangiGun: "3-14-2022",
    avgArray: 6281,
    greaterAvgArray: 9024,
  },
  {
    filename: "Felis.jpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Felis.jpeg",
    hangiGun: "8-14-2022",
    avgArray: 998,
    greaterAvgArray: 9533,
  },
  {
    filename: "MontesNasceturRidiculus.png",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/MontesNasceturRidiculus.png",
    hangiGun: "8-23-2022",
    avgArray: 6412,
    greaterAvgArray: 7676,
  },
  {
    filename: "Vulputate.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Vulputate.mp3",
    hangiGun: "4-6-2022",
    avgArray: 1010,
    greaterAvgArray: 1928,
  },
  {
    filename: "EuOrciMauris.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/EuOrciMauris.avi",
    hangiGun: "1-17-2023",
    avgArray: 995,
    greaterAvgArray: 736,
  },
  {
    filename: "SapienDignissim.txt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/SapienDignissim.txt",
    hangiGun: "9-15-2022",
    avgArray: 6750,
    greaterAvgArray: 4856,
  },
  {
    filename: "Nunc.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Nunc.avi",
    hangiGun: "9-21-2022",
    avgArray: 250,
    greaterAvgArray: 9174,
  },
  {
    filename: "PraesentLectus.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/PraesentLectus.mp3",
    hangiGun: "7-14-2022",
    avgArray: 1878,
    greaterAvgArray: 2368,
  },
  {
    filename: "NislNuncRhoncus.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/NislNuncRhoncus.mp3",
    hangiGun: "1-25-2023",
    avgArray: 1682,
    greaterAvgArray: 7721,
  },
  {
    filename: "Sodales.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Sodales.mp3",
    hangiGun: "5-3-2022",
    avgArray: 2552,
    greaterAvgArray: 1978,
  },
  {
    filename: "In.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/In.avi",
    hangiGun: "8-25-2022",
    avgArray: 102,
    greaterAvgArray: 4494,
  },
  {
    filename: "VulputateLuctusCum.mov",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/VulputateLuctusCum.mov",
    hangiGun: "1-3-2023",
    avgArray: 9139,
    greaterAvgArray: 4289,
  },
  {
    filename: "Vestibulum.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Vestibulum.mp3",
    hangiGun: "3-15-2022",
    avgArray: 4263,
    greaterAvgArray: 5969,
  },
  {
    filename: "NullaMollis.tiff",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/NullaMollis.tiff",
    hangiGun: "3-13-2022",
    avgArray: 8028,
    greaterAvgArray: 1018,
  },
  {
    filename: "PedeJusto.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/PedeJusto.avi",
    hangiGun: "1-13-2023",
    avgArray: 5925,
    greaterAvgArray: 4441,
  },
  {
    filename: "ImperdietNullamOrci.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/ImperdietNullamOrci.xls",
    hangiGun: "9-23-2022",
    avgArray: 3171,
    greaterAvgArray: 1728,
  },
  {
    filename: "Et.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Et.ppt",
    hangiGun: "9-25-2022",
    avgArray: 7741,
    greaterAvgArray: 7239,
  },
  {
    filename: "Vestibulum.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Vestibulum.avi",
    hangiGun: "9-10-2022",
    avgArray: 3637,
    greaterAvgArray: 6886,
  },
  {
    filename: "InLiberoUt.mpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/InLiberoUt.mpeg",
    hangiGun: "1-19-2023",
    avgArray: 4731,
    greaterAvgArray: 6254,
  },
  {
    filename: "EuTincidunt.tiff",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/EuTincidunt.tiff",
    hangiGun: "3-28-2022",
    avgArray: 1783,
    greaterAvgArray: 6503,
  },
  {
    filename: "SapienNonMi.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/SapienNonMi.mp3",
    hangiGun: "4-29-2022",
    avgArray: 2746,
    greaterAvgArray: 6613,
  },
  {
    filename: "TurpisEnim.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/TurpisEnim.xls",
    hangiGun: "4-13-2022",
    avgArray: 3202,
    greaterAvgArray: 69,
  },
  {
    filename: "Quam.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Quam.xls",
    hangiGun: "4-9-2022",
    avgArray: 9998,
    greaterAvgArray: 8096,
  },
  {
    filename: "QuamSuspendissePotenti.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/QuamSuspendissePotenti.avi",
    hangiGun: "10-8-2022",
    avgArray: 8800,
    greaterAvgArray: 3018,
  },
  {
    filename: "Mauris.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Mauris.avi",
    hangiGun: "4-7-2022",
    avgArray: 2658,
    greaterAvgArray: 2015,
  },
  {
    filename: "Sit.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Sit.ppt",
    hangiGun: "7-24-2022",
    avgArray: 244,
    greaterAvgArray: 8774,
  },
  {
    filename: "BlanditUltrices.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/BlanditUltrices.avi",
    hangiGun: "3-11-2022",
    avgArray: 3197,
    greaterAvgArray: 3195,
  },
  {
    filename: "Ac.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Ac.avi",
    hangiGun: "1-17-2023",
    avgArray: 4716,
    greaterAvgArray: 5230,
  },
  {
    filename: "SedSagittisNam.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/SedSagittisNam.ppt",
    hangiGun: "9-1-2022",
    avgArray: 5851,
    greaterAvgArray: 7984,
  },
  {
    filename: "Consequat.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Consequat.xls",
    hangiGun: "6-10-2022",
    avgArray: 8482,
    greaterAvgArray: 8895,
  },
  {
    filename: "Aliquet.txt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Aliquet.txt",
    hangiGun: "3-11-2022",
    avgArray: 2319,
    greaterAvgArray: 5225,
  },
  {
    filename: "NonummyMaecenasTincidunt.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/NonummyMaecenasTincidunt.ppt",
    hangiGun: "2-27-2022",
    avgArray: 1191,
    greaterAvgArray: 2490,
  },
  {
    filename: "QuamNec.pdf",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/QuamNec.pdf",
    hangiGun: "10-22-2022",
    avgArray: 1984,
    greaterAvgArray: 9884,
  },
  {
    filename: "EnimBlanditMi.tiff",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/EnimBlanditMi.tiff",
    hangiGun: "10-25-2022",
    avgArray: 4309,
    greaterAvgArray: 6778,
  },
  {
    filename: "DuiLuctus.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/DuiLuctus.ppt",
    hangiGun: "4-23-2022",
    avgArray: 7976,
    greaterAvgArray: 3174,
  },
  {
    filename: "Praesent.tiff",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Praesent.tiff",
    hangiGun: "6-18-2022",
    avgArray: 2450,
    greaterAvgArray: 9901,
  },
  {
    filename: "Sem.pdf",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Sem.pdf",
    hangiGun: "3-22-2022",
    avgArray: 1847,
    greaterAvgArray: 5348,
  },
  {
    filename: "MagnisDis.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/MagnisDis.ppt",
    hangiGun: "5-6-2022",
    avgArray: 2140,
    greaterAvgArray: 268,
  },
  {
    filename: "LiberoQuis.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/LiberoQuis.avi",
    hangiGun: "7-19-2022",
    avgArray: 7942,
    greaterAvgArray: 8196,
  },
  {
    filename: "Nulla.pdf",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Nulla.pdf",
    hangiGun: "7-1-2022",
    avgArray: 7695,
    greaterAvgArray: 2427,
  },
  {
    filename: "NatoquePenatibus.tiff",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/NatoquePenatibus.tiff",
    hangiGun: "4-12-2022",
    avgArray: 9126,
    greaterAvgArray: 951,
  },
  {
    filename: "Suspendisse.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Suspendisse.xls",
    hangiGun: "6-10-2022",
    avgArray: 3642,
    greaterAvgArray: 1650,
  },
  {
    filename: "AtDolor.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/AtDolor.avi",
    hangiGun: "2-11-2022",
    avgArray: 1358,
    greaterAvgArray: 6474,
  },
  {
    filename: "VulputateUtUltrices.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/VulputateUtUltrices.avi",
    hangiGun: "10-28-2022",
    avgArray: 3807,
    greaterAvgArray: 7805,
  },
  {
    filename: "TristiqueEstEt.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/TristiqueEstEt.xls",
    hangiGun: "4-14-2022",
    avgArray: 8903,
    greaterAvgArray: 5334,
  },
  {
    filename: "Diam.gif",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Diam.gif",
    hangiGun: "1-24-2023",
    avgArray: 7768,
    greaterAvgArray: 4881,
  },
  {
    filename: "TellusNulla.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/TellusNulla.avi",
    hangiGun: "10-1-2022",
    avgArray: 1752,
    greaterAvgArray: 3033,
  },
  {
    filename: "UltricesPhasellusId.jpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/UltricesPhasellusId.jpeg",
    hangiGun: "1-3-2023",
    avgArray: 9830,
    greaterAvgArray: 879,
  },
  {
    filename: "InPorttitor.pdf",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/InPorttitor.pdf",
    hangiGun: "11-12-2022",
    avgArray: 5114,
    greaterAvgArray: 7646,
  },
  {
    filename: "VelAugue.txt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/VelAugue.txt",
    hangiGun: "6-28-2022",
    avgArray: 9616,
    greaterAvgArray: 6484,
  },
  {
    filename: "Sit.jpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Sit.jpeg",
    hangiGun: "6-2-2022",
    avgArray: 1612,
    greaterAvgArray: 895,
  },
  {
    filename: "LuctusTinciduntNulla.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/LuctusTinciduntNulla.avi",
    hangiGun: "11-17-2022",
    avgArray: 8971,
    greaterAvgArray: 7577,
  },
  {
    filename: "PretiumIaculis.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/PretiumIaculis.xls",
    hangiGun: "4-29-2022",
    avgArray: 7634,
    greaterAvgArray: 6645,
  },
  {
    filename: "Nascetur.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Nascetur.mp3",
    hangiGun: "12-23-2022",
    avgArray: 8568,
    greaterAvgArray: 7948,
  },
  {
    filename: "Turpis.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Turpis.ppt",
    hangiGun: "4-25-2022",
    avgArray: 7211,
    greaterAvgArray: 565,
  },
  {
    filename: "VestibulumAnteIpsum.jpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/VestibulumAnteIpsum.jpeg",
    hangiGun: "10-24-2022",
    avgArray: 949,
    greaterAvgArray: 8720,
  },
  {
    filename: "SemperSapien.mov",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/SemperSapien.mov",
    hangiGun: "12-6-2022",
    avgArray: 8043,
    greaterAvgArray: 5815,
  },
  {
    filename: "SuspendissePotenti.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/SuspendissePotenti.ppt",
    hangiGun: "11-4-2022",
    avgArray: 8678,
    greaterAvgArray: 7015,
  },
  {
    filename: "Sed.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Sed.mp3",
    hangiGun: "10-21-2022",
    avgArray: 6903,
    greaterAvgArray: 7532,
  },
  {
    filename: "AmetLobortis.pdf",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/AmetLobortis.pdf",
    hangiGun: "6-14-2022",
    avgArray: 1489,
    greaterAvgArray: 6283,
  },
  {
    filename: "Eget.jpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Eget.jpeg",
    hangiGun: "5-21-2022",
    avgArray: 8892,
    greaterAvgArray: 3081,
  },
  {
    filename: "AmetEros.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/AmetEros.mp3",
    hangiGun: "12-13-2022",
    avgArray: 388,
    greaterAvgArray: 4028,
  },
  {
    filename: "ALibero.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/ALibero.avi",
    hangiGun: "12-22-2022",
    avgArray: 1502,
    greaterAvgArray: 6156,
  },
  {
    filename: "CubiliaCuraeNulla.txt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/CubiliaCuraeNulla.txt",
    hangiGun: "2-14-2022",
    avgArray: 9043,
    greaterAvgArray: 84,
  },
  {
    filename: "NonPretium.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/NonPretium.mp3",
    hangiGun: "10-9-2022",
    avgArray: 1204,
    greaterAvgArray: 8437,
  },
  {
    filename: "AmetLobortisSapien.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/AmetLobortisSapien.ppt",
    hangiGun: "10-12-2022",
    avgArray: 3615,
    greaterAvgArray: 3100,
  },
  {
    filename: "Vivamus.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Vivamus.avi",
    hangiGun: "9-18-2022",
    avgArray: 9446,
    greaterAvgArray: 8019,
  },
  {
    filename: "VelitId.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/VelitId.avi",
    hangiGun: "3-11-2022",
    avgArray: 6640,
    greaterAvgArray: 482,
  },
  {
    filename: "AcTellusSemper.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/AcTellusSemper.xls",
    hangiGun: "1-20-2023",
    avgArray: 5554,
    greaterAvgArray: 9301,
  },
  {
    filename: "PortaVolutpat.mov",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/PortaVolutpat.mov",
    hangiGun: "12-27-2022",
    avgArray: 8303,
    greaterAvgArray: 5868,
  },
  {
    filename: "MattisPulvinar.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/MattisPulvinar.avi",
    hangiGun: "8-8-2022",
    avgArray: 1111,
    greaterAvgArray: 6481,
  },
  {
    filename: "EuNibh.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/EuNibh.ppt",
    hangiGun: "11-13-2022",
    avgArray: 2447,
    greaterAvgArray: 2447,
  },
  {
    filename: "EgetTempusVel.tiff",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/EgetTempusVel.tiff",
    hangiGun: "12-8-2022",
    avgArray: 7838,
    greaterAvgArray: 5002,
  },
  {
    filename: "Sem.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Sem.ppt",
    hangiGun: "2-27-2022",
    avgArray: 6067,
    greaterAvgArray: 1258,
  },
  {
    filename: "PedeUllamcorper.txt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/PedeUllamcorper.txt",
    hangiGun: "12-23-2022",
    avgArray: 5025,
    greaterAvgArray: 5705,
  },
  {
    filename: "IaculisCongue.jpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/IaculisCongue.jpeg",
    hangiGun: "10-27-2022",
    avgArray: 6545,
    greaterAvgArray: 1909,
  },
  {
    filename: "Nam.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Nam.avi",
    hangiGun: "7-9-2022",
    avgArray: 195,
    greaterAvgArray: 1626,
  },
  {
    filename: "In.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/In.mp3",
    hangiGun: "12-16-2022",
    avgArray: 3891,
    greaterAvgArray: 4035,
  },
  {
    filename: "NullaNeque.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/NullaNeque.xls",
    hangiGun: "12-22-2022",
    avgArray: 4181,
    greaterAvgArray: 241,
  },
  {
    filename: "Metus.png",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Metus.png",
    hangiGun: "12-22-2022",
    avgArray: 2130,
    greaterAvgArray: 7201,
  },
  {
    filename: "InSapienIaculis.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/InSapienIaculis.ppt",
    hangiGun: "5-5-2022",
    avgArray: 378,
    greaterAvgArray: 6609,
  },
  {
    filename: "In.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/In.avi",
    hangiGun: "11-9-2022",
    avgArray: 7283,
    greaterAvgArray: 3088,
  },
  {
    filename: "SitAmet.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/SitAmet.mp3",
    hangiGun: "12-2-2022",
    avgArray: 1670,
    greaterAvgArray: 7927,
  },
  {
    filename: "QuisTurpisSed.txt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/QuisTurpisSed.txt",
    hangiGun: "1-4-2023",
    avgArray: 5597,
    greaterAvgArray: 8415,
  },
  {
    filename: "PellentesqueEget.tiff",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/PellentesqueEget.tiff",
    hangiGun: "8-15-2022",
    avgArray: 4641,
    greaterAvgArray: 2703,
  },
  {
    filename: "Lorem.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Lorem.xls",
    hangiGun: "2-5-2023",
    avgArray: 2546,
    greaterAvgArray: 6217,
  },
  {
    filename: "Tempus.txt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Tempus.txt",
    hangiGun: "1-1-2023",
    avgArray: 7875,
    greaterAvgArray: 6834,
  },
  {
    filename: "IpsumAliquamNon.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/IpsumAliquamNon.ppt",
    hangiGun: "9-20-2022",
    avgArray: 8867,
    greaterAvgArray: 4815,
  },
  {
    filename: "Proin.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Proin.ppt",
    hangiGun: "9-13-2022",
    avgArray: 6180,
    greaterAvgArray: 4857,
  },
  {
    filename: "DonecQuisOrci.png",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/DonecQuisOrci.png",
    hangiGun: "9-6-2022",
    avgArray: 3576,
    greaterAvgArray: 1605,
  },
  {
    filename: "TristiqueInTempus.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/TristiqueInTempus.mp3",
    hangiGun: "4-5-2022",
    avgArray: 33,
    greaterAvgArray: 5384,
  },
  {
    filename: "CursusUrna.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/CursusUrna.xls",
    hangiGun: "6-13-2022",
    avgArray: 2837,
    greaterAvgArray: 4243,
  },
  {
    filename: "VelitNecNisi.jpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/VelitNecNisi.jpeg",
    hangiGun: "3-24-2022",
    avgArray: 8003,
    greaterAvgArray: 848,
  },
  {
    filename: "Pede.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Pede.mp3",
    hangiGun: "10-11-2022",
    avgArray: 1033,
    greaterAvgArray: 884,
  },
  {
    filename: "QuamSapien.doc",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/QuamSapien.doc",
    hangiGun: "11-4-2022",
    avgArray: 7315,
    greaterAvgArray: 1618,
  },
  {
    filename: "Ultrices.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Ultrices.ppt",
    hangiGun: "12-5-2022",
    avgArray: 6160,
    greaterAvgArray: 7404,
  },
  {
    filename: "Mollis.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Mollis.ppt",
    hangiGun: "6-6-2022",
    avgArray: 9366,
    greaterAvgArray: 6122,
  },
  {
    filename: "DuiVel.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/DuiVel.avi",
    hangiGun: "5-24-2022",
    avgArray: 4888,
    greaterAvgArray: 3656,
  },
  {
    filename: "DisParturient.mov",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/DisParturient.mov",
    hangiGun: "9-29-2022",
    avgArray: 2608,
    greaterAvgArray: 4076,
  },
  {
    filename: "DiamIn.txt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/DiamIn.txt",
    hangiGun: "8-5-2022",
    avgArray: 4534,
    greaterAvgArray: 3898,
  },
  {
    filename: "CursusVestibulumProin.gif",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/CursusVestibulumProin.gif",
    hangiGun: "4-23-2022",
    avgArray: 7629,
    greaterAvgArray: 9733,
  },
  {
    filename: "Adipiscing.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Adipiscing.xls",
    hangiGun: "2-22-2022",
    avgArray: 209,
    greaterAvgArray: 1002,
  },
  {
    filename: "Lacus.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Lacus.xls",
    hangiGun: "11-22-2022",
    avgArray: 174,
    greaterAvgArray: 6016,
  },
  {
    filename: "UltricesVel.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/UltricesVel.avi",
    hangiGun: "9-29-2022",
    avgArray: 5117,
    greaterAvgArray: 3280,
  },
  {
    filename: "Curabitur.jpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Curabitur.jpeg",
    hangiGun: "8-25-2022",
    avgArray: 6101,
    greaterAvgArray: 6504,
  },
  {
    filename: "Non.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Non.xls",
    hangiGun: "10-15-2022",
    avgArray: 4863,
    greaterAvgArray: 8871,
  },
  {
    filename: "BibendumMorbiNon.mpeg",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/BibendumMorbiNon.mpeg",
    hangiGun: "2-5-2023",
    avgArray: 2077,
    greaterAvgArray: 8006,
  },
  {
    filename: "DuisConsequatDui.txt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/DuisConsequatDui.txt",
    hangiGun: "11-14-2022",
    avgArray: 8104,
    greaterAvgArray: 5859,
  },
  {
    filename: "Varius.pdf",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Varius.pdf",
    hangiGun: "1-12-2023",
    avgArray: 8787,
    greaterAvgArray: 6609,
  },
  {
    filename: "AIpsumInteger.mov",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/AIpsumInteger.mov",
    hangiGun: "5-1-2022",
    avgArray: 3706,
    greaterAvgArray: 2868,
  },
  {
    filename: "AmetConsectetuer.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/AmetConsectetuer.mp3",
    hangiGun: "6-29-2022",
    avgArray: 3263,
    greaterAvgArray: 6498,
  },
  {
    filename: "Duis.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Duis.ppt",
    hangiGun: "6-16-2022",
    avgArray: 6363,
    greaterAvgArray: 2820,
  },
  {
    filename: "AnteIpsumPrimis.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/AnteIpsumPrimis.avi",
    hangiGun: "3-12-2022",
    avgArray: 7686,
    greaterAvgArray: 4247,
  },
  {
    filename: "EleifendDonecUt.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/EleifendDonecUt.mp3",
    hangiGun: "3-18-2022",
    avgArray: 7361,
    greaterAvgArray: 9985,
  },
  {
    filename: "Eget.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Eget.mp3",
    hangiGun: "7-12-2022",
    avgArray: 3052,
    greaterAvgArray: 8593,
  },
  {
    filename: "NequeAenean.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/NequeAenean.avi",
    hangiGun: "4-7-2022",
    avgArray: 3150,
    greaterAvgArray: 1378,
  },
  {
    filename: "AIpsumInteger.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/AIpsumInteger.avi",
    hangiGun: "3-27-2022",
    avgArray: 1040,
    greaterAvgArray: 6146,
  },
  {
    filename: "EgetElitSodales.ppt",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/EgetElitSodales.ppt",
    hangiGun: "7-29-2022",
    avgArray: 3899,
    greaterAvgArray: 6022,
  },
  {
    filename: "InFaucibus.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/InFaucibus.mp3",
    hangiGun: "8-11-2022",
    avgArray: 7308,
    greaterAvgArray: 5966,
  },
  {
    filename: "FaucibusOrciLuctus.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/FaucibusOrciLuctus.mp3",
    hangiGun: "2-11-2022",
    avgArray: 7699,
    greaterAvgArray: 6877,
  },
  {
    filename: "Sapien.mp3",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/Sapien.mp3",
    hangiGun: "1-20-2023",
    avgArray: 5024,
    greaterAvgArray: 1726,
  },
  {
    filename: "LigulaNecSem.avi",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/LigulaNecSem.avi",
    hangiGun: "2-25-2022",
    avgArray: 5089,
    greaterAvgArray: 2755,
  },
  {
    filename: "EtUltricesPosuere.xls",
    dosyaAdiniBul: "C:/Users/johnsmith/Documents/EtUltricesPosuere.xls",
    hangiGun: "5-8-2022",
    avgArray: 3423,
    greaterAvgArray: 2601,
  },
];
export const filenames = [...data.map(({ dosyaAdiniBul }) => dosyaAdiniBul)];
export const numbersAvg = [...data.map(({ avgArray }) => avgArray)];
export const numbersGreaterAvg = [
  ...data.map(({ greaterAvgArray }) => greaterAvgArray),
];
export const dates = [...data.map(({ hangiGun }) => hangiGun)];

// export default data;
/* 
console.log(filenames)
console.log(numberAvg)
console.log(numbersGAvg)
console.log(dates)
*/
